[package]
org = "ballerinax"
name = "eventapi.interop.handler"
version = "0.5.0"
export= ["eventapi.interop.handler"]

[[platform.java11.dependency]]
path = "./java-wrapper/build/libs/java-wrapper-0.9.0-beta.3-SNAPSHOT.jar"
groupId = "io.ballerinax.slack"
artifactId = "java-wrapper"
version = "0.9.9-SNAPSHOT"

[build-options]
observabilityIncluded = true
